version: '3.9'

services:
  chromadb:
    build: ./chromadb
    volumes:
      - ./chroma_data:/chroma_data
    ports:
      - "8000:8000"

  ollama:
    build: ./ollama
    ports:
      - "11434:11434"

  flowise:
    build: ./flowise
    volumes:
      - ./flowise_data:/root/.flowise
    ports:
      - "3000:3000"
    environment:
      - DATABASE_PATH=/root/.flowise/database.sqlite
    depends_on:
      - chromadb
      - ollama

  n8n:
    build: ./n8n
    ports:
      - "5678:5678"
    volumes:
      - ./n8n_data:/home/node/.n8n
    depends_on:
      - flowise

  frontend:
    build: ./frontend
    ports:
      - "8080:80"
    depends_on:
      - flowise
