services:
  - type: web
    name: frontend
    env: docker
    repo: https://github.com/YOUR_USERNAME/rag-chatbot.git
    dockerfilePath: ./frontend/Dockerfile
    branch: main
    plan: free
    healthCheckPath: /
    envVars: []

  - type: web
    name: flowise
    env: docker
    repo: https://github.com/YOUR_USERNAME/rag-chatbot.git
    dockerCommand: docker run -p 3000:3000 flowiseai/flowise
    branch: main
    plan: free
    envVars: []

  - type: web
    name: ollama
    env: docker
    repo: https://github.com/YOUR_USERNAME/rag-chatbot.git
    dockerCommand: docker run -p 11434:11434 ollama/ollama
    branch: main
    plan: free
    envVars: []

  - type: web
    name: chromadb
    env: docker
    repo: https://github.com/YOUR_USERNAME/rag-chatbot.git
    dockerCommand: docker run -p 8000:8000 chromadb/chroma
    branch: main
    plan: free
    envVars: []

  - type: web
    name: n8n
    env: docker
    repo: https://github.com/YOUR_USERNAME/rag-chatbot.git
    dockerCommand: docker run -p 5678:5678 n8nio/n8n
    branch: main
    plan: free
    envVars:
      - key: GENERIC_TIMEZONE
        value: Asia/Kolkata
